#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Nov  3 17:40:27 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class MyHTMLFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyHTMLFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.button_6 = wx.Button(self, -1, "Previous")
        self.button_7 = wx.Button(self, -1, "Next")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyHTMLFrame.__set_properties
        self.SetTitle("Work space")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyHTMLFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.button_6, 0, 0, 0)
        sizer_4.Add(self.button_7, 0, 0, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyHTMLFrame


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Feedback")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        self.Layout()
        # end wxGlade

# end of class MyDialog


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.starting_menubar = wx.MenuBar()
        self.SetMenuBar(self.starting_menubar)
        # Menu Bar end
        self.starting_frame_statusbar = self.CreateStatusBar(1, 0)
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap(u"logo.png", wx.BITMAP_TYPE_ANY))
        self.button_1 = wx.Button(self, -1, "Billing")
        self.button_2 = wx.Button(self, -1, "Current Accounts")
        self.button_3 = wx.Button(self, -1, "Customers")
        self.button_4 = wx.Button(self, -1, "Articles")
        self.button_5 = wx.Button(self, -1, "Queries")
        self.button_8 = wx.Button(self, -1, "Movements")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(u"GestiónLibre")
        self.starting_frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        starting_frame_statusbar_fields = ["Status bar text"]
        for i in range(len(starting_frame_statusbar_fields)):
            self.starting_frame_statusbar.SetStatusText(starting_frame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.bitmap_1, 0, 0, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_2.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.button_3, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.button_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.button_5, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(self.button_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame


if __name__ == "__main__":
    GestionLibre = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    starting_frame = MyFrame(None, -1, "")
    GestionLibre.SetTopWindow(starting_frame)
    starting_frame.Show()
    GestionLibre.MainLoop()
